/*
 * This source file was generated by the Gradle 'init' task
 */
package dam.optativa;

import org.junit.Test;
import static org.junit.Assert.*;

public class DiscountCalculatorTest {
    @Test public void studentDiscount() {
        DiscountCalculator calc = new DiscountCalculator();
        double result = calc.calculate(100, true);
        assertEquals(80.0, result, 0.001);
    }
    @Test public void normalPersonDiscount() {
        DiscountCalculator calc = new DiscountCalculator();
        double result = calc.calculate(100.0, false);
        assertEquals(95.0, result, 0.001);
    }
    @Test public void priceIsZero() {
        DiscountCalculator calc = new DiscountCalculator();
        double result = calc.calculate(0.0, false);
        assertEquals(0.0, result, 0.001);
    }
    @Test public void priceIsNegative() {
        DiscountCalculator calc = new DiscountCalculator();
        try {
            double result = calc.calculate(-100.0, false);
            fail("El numero no puede ser negativo");
        } catch (Exception e) {
            
        }
        
    }
}
